
MINIMAP_SIZE_FACTOR_PLAYER = 0.1
MINIMAP_SIZE_FACTOR_SPOT_MARKER = 0.045
MINIMAP_SIZE_FACTOR_EDGE_INDICATOR = 0.08
MINIMAP_EDGE_INDICATOR_TEXTURE = "MiniMap\\media\\edge_indicator_triangle.dds"
MINIMAP_SEGMENT_TEXTURE = "MiniMap\\media\\segment.dds"
MINIMAP_SPOT_DUPLICATE_THRESHOLD = 0.0005
MINIMAP_CITY_ZOOM = 4
MINIMAP_REFRESH_MS = 500
