
MINIMAP_SIZE_FACTOR_PLAYER = 0.1
MINIMAP_SIZE_FACTOR_SPOT_MARKER = 0.045
MINIMAP_SIZE_FACTOR_EDGE_INDICATOR = 0.2
MINIMAP_SIZE_FACTOR_INSIDE_MARKER = 0.04
MINIMAP_SEGMENT_TEXTURE = "MiniMap\\media\\segment.dds"
MINIMAP_SPOT_DUPLICATE_THRESHOLD = 0.0005
MINIMAP_CITY_ZOOM = 4
MINIMAP_REFRESH_MS = 500

MINIMAP_TEXTURE_QUEST = "EsoUI/Art/Compass/quest_icon_assisted.dds"
MINIMAP_TEXTURE_WAYSHRINE = "EsoUI/Art/Compass/quest_icon_assisted.dds"
MINIMAP_TEXTURE_NPC = "EsoUI/Art/Compass/quest_icon_assisted.dds"

MINIMAP_EDGE_INDICATOR_QUEST = "activeQuest"
MINIMAP_EDGE_INDICATOR_WAYSHRINE = "wayshrine"
MINIMAP_EDGE_INDICATOR_ROUTE = "activeRoute"
MINIMAP_EDGE_INDICATOR_NPC = "npcFind"

MINIMAP_QUEST_COLOR = { 1, 1, 1, 1 }
MINIMAP_WAYSHRINE_COLOR = { 0.5, 0.8, 1, 1 }
MINIMAP_ROUTE_COLOR = { 0.25, 0.25, 0.25, 1 }
MINIMAP_NPC_FIND_COLOR = { 1, 0.2, 0.2, 1 }
